# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'bundleDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Depending on how your project is organized, your node_modules directory may be
  # somewhere else; tell CocoaPods where you've installed react-native from npm
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # Pods for bundleDemo

  target 'bundleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bundleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
